export const PROFILE_GET = 'PROFILE_GET';
export const PROFILE_UPDATE_DESCRIPTION = 'PROFILE_UPDATE_DESCRIPTION';
export const PROFILE_GET_COMMENTS_FOR_USER = 'PROFILE_GET_COMMENTS_FOR_USER';
export const PROFILE_GET_UPLOADS_FOR_USER = 'PROFILE_GET_UPLOADS_FOR_USER';
export const PROFILE_GET_VIDEOS_FOR_USER = 'PROFILE_GET_VIDEOS_FOR_USER';
